[platformio]
default_envs = nanoatmega328

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
monitor_speed = 115200
upload_speed = 57600
upload_port = COM11

lib_deps =
	coryjfowler/mcp_can
