; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_src_filter =
	+<can_handler.cpp>
	+<imu_handler.cpp>
	+<main.cpp>
	+<utils.cpp>

; Usa tamanho de flash padrão da placa (esp32doit-devkit-v1 = 4MB)
board_build.partitions = huge_app.csv

; ---- Stack Overflow Check (FreeRTOS)  ----
; Modo 2: escreve padrão na stack + verifica na troca de contexto com nome da task
build_flags =
	-D CONFIG_FREERTOS_ENABLE_STATIC_TASK_CLEAN_UP=0
	-D configCHECK_FOR_STACK_OVERFLOW=2
	-D CONFIG_ESP_TASK_WDT_TIMEOUT_S=5
	-D CORE_DEBUG_LEVEL=3

lib_deps = 
	adafruit/Adafruit BNO08x@^1.2.5
	pierremolinaro/ACAN2515@^2.1.5

[env:esp32doit-devkit-v1-baremetal]
platform = espressif32
board = esp32doit-devkit-v1
framework = espidf
monitor_speed = 115200
build_src_filter =
	-<*>
	+<main_baremetal.c>
